### ISSUE TITLE
yarn をバージョンアップしよう

### ISSUE THREAD

**Issue by a01sa01to** [saitamau-maximum/public-website#10]
今 yarn v1 が使われているが、 PnP により `yarn install` がめちゃくちゃ速くなる最新版にしよう

**Comment by batora9** [comment]
Markdown libraries for Maximumを使うためにPATが必要だが、yarnを使っていると`.npmrc`と`npmrc.pages`は競合してしまう可能性があるため、yarnからnpmへ移行する。

**Comment by sor4chi** [comment]
> Markdown libraries for Maximumを使うためにPATが必要だが、yarnを使っていると.npmrcとnpmrc.pagesは競合してしまう可能性があるため、yarnからnpmへ移行する。

補足：npmでwebsiteが上手くいってて、同じ方法でyarnだと動かないためパケマネのせいだと決めつけて移行。どうせyarn 4にするなら今のタイミングでパケマネ変えてもいいよねっていう思案
