### ISSUE TITLE
みんなの資格情報 (AP とか) をどこかに書く

### ISSUE THREAD

**Issue by a01sa01to** [saitamau-maximum/public-website#109]

**Comment by sor4chi** [comment]
情報処理安全確保支援士（登録セキスペ）: 1人
応用情報技術者: 7人
基本情報技術者: 3人

**Comment by sor4chi** [comment]
Public Website上のどこかに実績として書くでOK

**Comment by shigekk** [comment]
Achievementsに「参加した大会」という項目があるので、「部員が保有する資格」という項目を追加するのはどうでしょう？

**Comment by sor4chi** [comment]
一旦closeします
