### ISSUE TITLE
News一覧ページを作成しよう

### ISSUE THREAD

**Issue by yukikamome316** [saitamau-maximum/public-website#22]
## 要件
#17 と同様に実装してください。

**Comment by yukikamome316** [comment]
新歓に向けた情報を載せるissueだから残しておこう

**Comment by yukikamome316** [comment]
> @yukikamome316 
> 
> 「News一覧ページを作成しよう」を#21 でやってしまいました
> 
> このissueどうしますか？

新歓に向けた情報を載せるissueだから、これは残しておこう

**Comment by batora9** [comment]
@yukikamome316 「MarkdownをNewsページに表示させる」は新しくissue立てますか？

**Comment by yukikamome316** [comment]
> @yukikamome316 「MarkdownをNewsページに表示させる」は新しくissue立てますか？

忘れてた、お願いします

**Comment by yukikamome316** [comment]
@hana-rs 
新歓のことウェブサイトに書くといいかも？
